### ISSUE TITLE
VIRUS DONT RUN

### ISSUE THREAD

**Issue by kyron15** [420World69/Tiktok-Unfilter-Api#3]
PLEASE DONT RUN THIS IT CONTAINS A MALICIOUS PYTHON PACKAGE

**Comment by jordanandvesko** [comment]
mhm the pyshftuler.

**Comment by kyron15** [comment]
> mhm the pyshftuler.

yeah i’m gonna get their webhook and destroy it

**Comment by jordanandvesko** [comment]
ik how to disable both the server and the webhook. should i do it?

**Comment by kyron15** [comment]
> ik how to disable both the server and the webhook. should i do it?

sure but do it under a vm and if you need to login to a discord account use an alt
